# Generated by Django 6.0.3 on 2026-03-09 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='StoreStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_customers', models.PositiveIntegerField(default=2500, verbose_name='Clientes Felizes')),
                ('pastries_sold', models.PositiveIntegerField(default=15000, verbose_name='Doces Vendidos')),
                ('years_experience', models.PositiveIntegerField(default=8, verbose_name='Anos de Experiência')),
                ('exclusive_recipes', models.PositiveIntegerField(default=120, verbose_name='Receitas Exclusivas')),
            ],
            options={
                'verbose_name': 'Estatística da Loja',
                'verbose_name_plural': 'Estatísticas da Loja',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ERP.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_link', to='base.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='base.baseproduct')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
