# Generated by Django 5.2 on 2026-03-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_financebox_financelog'),
        ('ERP', '0003_recipe_recipeingredient'),
    ]

    operations = [
    ]
