# Generated by Django 5.2 on 2026-03-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_merge_20260318_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financebox',
            options={'verbose_name': 'Caixa Financeiro', 'verbose_name_plural': 'Caixas Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='financelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log Financeiro', 'verbose_name_plural': 'Logs Financeiros'},
        ),
        migrations.AlterField(
            model_name='financebox',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='financelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
