# Generated by Django 5.2 on 2026-03-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclick',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_clicks', to='base.baseproduct'),
        ),
    ]
